### PR TITLE
Fix schedule timezone bug

### LINKED ISSUE #4: BUG: Milk at 4am PST or GMT?
### Summary

The text on the website says the cows are milked at 4am.

However, the cron expressions in the `ScheduledJobs` class are, by default, expressed in Zulu time (i.e. Coordinated Universal Time, aka Greenwich Mean Time).

We would prefer that to be in local time.  

### Expected Behavior

It should be 4am local time

### Current / Observed Behavior

It isn't 

### Steps to Reproduce

Look at the logs to see when the job actually ran.

### Implementation Notes

As explained [here](https://www.baeldung.com/spring-scheduled-tasks#schedule-a-task-using-cron-expressions) it's possible to include a timezone in the `@Scheduled` annotations.   The example given is:

```
@Scheduled(cron = "0 15 10 15 * ?", zone = "Europe/Paris")
```

The zone we want is this one: `America/Los_Angeles`

http://www.timezoneconverter.com/cgi-bin/zoneinfo?tz=America/Los_Angeles

It's ok to hard code it for now.  If we ever need to support another timezone, we can make this a configuration variable like the cron expressions are.

# To test

Check the logs for the scheduled jobs and see when they run.  If necessary, you can override the default schedule with configuration variables.  See the `src/main/resources/application.properties` file where you'll find expressions like these:

```
app.updateCowHealth.cron=${UPDATE_COW_HEALTH_CRON:${env.UPDATE_COW_HEALTH_CRON:0 0 0,12 * * *}}
app.milkTheCows.cron=${MILK_THE_COWS_CRON:${env.MILK_THE_COWS_CRON:0 0 4 * * *}}
```

and the corresponding entries in `src/main/resources/application-development.properties`

```
app.updateCowHealth.cron=${UPDATE_COW_HEALTH_CRON:${env.UPDATE_COW_HEALTH_CRON:0 */7 * * * *}}
app.milkTheCows.cron=${MILK_THE_COWS_CRON:${env.MILK_THE_COWS_CRON:0 */13 * * * *}}
```

For an explanation of the syntax `0 */13 * * * *` or `0 0 0,12 * * *` see 
https://spring.io/blog/2020/11/10/new-in-spring-5-3-improved-cron-expressions

### PR DESCRIPTION
**Pull request by yuanchenmeng**
## Overview
Time zone environmental variable is added in src/main/resources/application.properties

image

zone param is added for scheduled jobs

image

## Tests
Backend Test coverage & Mutation tests : 100%

## Linked Issues
Previous version of this PR: #41
Closes #4

### CODE REVIEW

**Review by publicqi — DISMISSED** [review]
It's a simple fix. lgtm

**Comment by yuanchenmeng** [comment]
Code changed, requested for CR.

**Review by iain801 — DISMISSED** [review]
Looks good to me, simple change

**Comment by yuanchenmeng** [comment]
Merge conflicts resolved

**Review by pconrad — CHANGES_REQUESTED** [review]
It appears that all of the changes in this PR were already made in a previous PR.... it appears that there are actually no changes here except formatting.  

Please let me know if I'm missing something.

If this is obsolete, let's close it.

**Comment by yuanchenmeng** [comment]
> 



> It appears that all of the changes in this PR were already made in a previous PR.... it appears that there are actually no changes here except formatting.
> 
> Please let me know if I'm missing something.
> 
> If this is obsolete, let's close it.

When I worked for this PR, initially I only changed cron value in schedule.js file. At the same time, Iain worked on schedule.js as well for CommonStats branch. We both agreed to add additional variables into springboot resource file. He made a commit into my PR so that my PR was consistent with his branch, link to the commit: 81ad12c123baf727616c7ed1b0ac97b9bc0fe008. 
Therefore, the timezone bug is already fixed in Iain's commonStats PR. However, as we addressed different issues in this case, I wonder if we can get points for this PR or just close it.

**Comment by pconrad** [comment]
> > 
> 
> > It appears that all of the changes in this PR were already made in a previous PR.... it appears that there are actually no changes here except formatting.
> > Please let me know if I'm missing something.
> > If this is obsolete, let's close it.
> 
> When I worked for this PR, initially I only changed cron value in schedule.js file. At the same time, Iain worked on schedule.js as well for CommonStats branch. We both agreed to add additional variables into springboot resource file. He made a commit into my PR so that my PR was consistent with his branch, link to the commit: [81ad12c](https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/commit/81ad12c123baf727616c7ed1b0ac97b9bc0fe008). Therefore, the timezone bug is already fixed in Iain's commonStats PR. However, as we addressed different issues in this case, I wonder if we can get points for this PR or just close it.

No.. there's literally no new functionality here.   It's exactly the same code, as far as I can see, just reformatted.   

In any case, the team already has so many points that I don't think it's going to be a big deal.  I'm going to just close this one.

**Pull request closed without merging**
