### PR TITLE
Updated Project Name to Happy Cows

### LINKED ISSUE #23: BUG: Is it Happy Cows or Happier Cows?
## Discussion
The URL and our names have always been Happy Cows. However, the site itself labels the game as Happier Cows. Which one is correct? We should be consistent with the name.

## Screenshots
We go to Happy Cows the URL and call it the Happy Cows game:
Screenshot 2023-08-11 at 1 38 28 AM

But the actual game calls itself Happier Cows:
Screenshot 2023-08-11 at 1 38 33 AM

### PR DESCRIPTION
**Pull request by dscpsyl**
## Overview
In this PR, the name of the project is updated in the UI. Officially, this is being confirmed as **Happy Cows** instead of **Happier Cows** after the migration. This PR changes the UI name in the nav bar, the footer, and the login card.

## Screenshots (Optional)
Screenshot 2023-08-15 at 10 31 43 PM

## Feedback Request (Optional)
Please let me know if I missed the name change anywhere.

## Tests
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Closes #23

### CODE REVIEW

**Comment by iain801** [comment]
I think it's called Happier Cows because it's a clone of the Happy Cows game. I think it mentions this in the Readme

**Review by MPriston — APPROVED** [review]
Pretty simples changes, no code breaking changes, LGTM

**Comment by dscpsyl** [comment]
> I think it's called Happier Cows because it's a clone of the Happy Cows game. I think it mentions this in the Readme

Yeah, and as we talked about on slack, the prof has said that now that this project is the current dev one, we should update it to be the official one.

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
