### PR TITLE
Chat message API

### LINKED ISSUE #46: FEATURE: MVP issues for Chat Backend
# Feature Summary 

The aim is to have a chat box on the user commons page so that admin and users can send messages between each other.

This issue targets the CRUD backend for the basic commons chat feature.

# Discussion

This is a big feature, so it should be broken up into multiple issues; the list below is one suggestion.

Remember "minimum viable product"; the first iteration of this would be a single chat room for each Commons, without DM features; just a global chat where everyone sees everything.   

The list below mentions "hiding" messages (rather than deleting them).  That's not part of MVP, so make sure that all of the MVP features get done first.  However, I do suggest including the `private boolean hidden;` field in the entity even in the first iteration; database changes later are much more disruptive (since we don't have a good database migration strategy yet), so it's better to include all of the fields you might need in the initial run.

To that end, we might also include these fields in the entity:

`private boolean dm;`
`private Long toUserId`

The `dm` field would initially always be false, and the toUserId field would be `null`; we'll use those fields later when/if we implement DMs (but that will be a separate Epic.)

##  CRUD backend for messages MVP

- [x] There is an entity/repository for a ChatMessage.  A ChatMessage should have an id, userId, commonsId and a message payload.   You can use the `@CreationTimestamp` technique to automatically get a timestamp on the message. 
- [x] Include these fields for future use:
       `private boolean hidden;`
       `private Long toUserId`
- [x] The entity/repository for a ChatMessage should also have a "hidden" field that is initially false.  (This is because rather than deleting messages, we want to just "mark them as hidden".   This is to prevent users from using the chat to harass other users by sending inappropriate messages and then deleting them; messages marked as hidden remain in the database (so that they can be retained as evidence) but are not shown.   
- [x] There is a backend POST endpoint `/api/chat/post` where any user can create a message for a particular commonsId, provided they are a member of that commons.  If they have not joined that commons, that should be a 403 error.  The `hidden` field is initially `false`.   The endpoint should take these parameters: `commonsId` and `content`.   The userId should be determined automatically from the currentUser service on the backend, and should not be passed as a parameter. The `dm` field should always be set to `false` right now, and the `toUserId` set to null.
- [x] There is a backend endpoint `/api/chat/get` that takes a commonsId as a param, for retrieving chat messages for a particular commons that operates similar to the backend endpoint for jobs, in that it is paged, and sorted.   The endpoint should retrieve the most recent messages first, and should exclude any "hidden" messages.  It should retrieve messages for a particular commons only if the user is a member of that commons, or the user is an admin, otherwise it should return a 403

### PR DESCRIPTION
**Pull request by dscpsyl**
## Overview

In this PR, we implement the MVP for the chat backend. There is a post request where users of a common and admins can post messages, a get for users and admins to get messages, a get for admins to get all messages, including the hidden ones, and a delete for admins to hide messages. Those that do not follow the specifications in #1 are not part of the MVP. They will later be updated to conform. 

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 

## Linked Issues

Closes #46

### CODE REVIEW

**Review by publicqi — APPROVED** [review]
lgtm

**Review by chriscerie — CHANGES_REQUESTED** [review]
This will result in orphaned records when an admin deletes commons. Define the cascade relationships between commons and chatmessage or add a todo to.

Similarly when a user is deleted, you'll either want to delete the user chats as well or anonymize the userId.

**Comment by dscpsyl** [comment]
> This will result in orphaned records when an admin deletes commons. Define the cascade relationships between commons and chatmessage or add a todo to.
> 
> Similarly when a user is deleted, you'll either want to delete the user chats as well or anonymize the userId.

@pconrad Could you advise on this, or let's talk about it on Tuesday? This was a problem that I had in mind but pushed it aside while making the MVP. Ik our goal was to never delete anything, but what should happen when a commons is deleted? Should the chat messages still be available in a separate state, or should they be deleted too? When we delete a user, should their info be deleted as well or also hidden, as this will affect how chat messages are changed? If a user is deleted, should their chat messages still be visible to other players in the commons but just with a "deleted user" tag or something else? For now I will put this as a todo as it doesn't effect the MVP or the additions that I will add over the weekend but we will need to address these relationships before this feature goes public. 

Regardless, everyone, take care and stay safe over the weekend! This tropical storm is looking to be a big one!

**Comment by chriscerie** [comment]
> When we delete a user, should their info be deleted as well or also hidden

There's privacy & compliance considerations related to not allowing users to completely remove their data. I'd suggest deleting user info completely.

> If a user is deleted, should their chat messages still be visible to other players in the commons but just with a "deleted user" tag or something else?

This is a good cross-team discussion point. Consider prior work - when you delete an instagram account, your comments also get deleted. With discord & github, they get anonymized.

**Comment by iain801** [comment]
I think anonymizing would be best, as we are hosting conversations (presumably), and they will not make sense if a user is deleted. Comments make sense to remove, as they do not generally build off one another. But chats, by definition, do.

**Comment by dscpsyl** [comment]
Closed as combined with #76. However, comments and discussions here still stand and will be referred back to.

**Pull request closed without merging**
